### ISSUE TITLE
why offset is a pointer?

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#10]
https://github.com/essserrr/Solutions/blob/e3672c5869e5400514b7a502ae751f9b2938f750/Project%201/bases/level/getLevelsFromGamepress.go#L91

what's the reason to use pointer to integer for offset?

**Comment by essserrr** [comment]
Cause getNextAsString should remember where it finished reading last time. In order to do this, it stores offset outside the function body. But it needs to write somehow into that variable (offset), so offset needed to be sent into the function as a pointer.
So, in the end, two functions are walking through HTML page: getNextAsString with rightOffset and leftOffset. Right one represents a key, and left one represents a value. After we get both, we add a full entry into the outputTable
