### ISSUE TITLE
else 

### ISSUE THREAD

**Issue by awskii** [essserrr/Solutions#6]
Same. Only once if statement will be used, you can omit else clause and write its body just after if statement. 
https://github.com/essserrr/Solutions/blob/ae915c2b9c738b836fa0262f18eda5348d52d0e4/Fib%202/fib.go#L17

**Comment by essserrr** [comment]
We need "else if" here since the block after i > 1 mustn't be evaluated for i == 1 and i == 0. So if we just drop "else if" it will be evaluated for both cases (0 and 1), returning panic since the map has not keys i-1 and i-2. If we change "else if" to "else", the block will be evaluated for i == 0, but again it causes panic. 
So we need major changes in the code structure to eliminate else if block. I`m not quite sure if it is more readable or not, but I did it.
